"""empty message

Revision ID: 0379e7b740ec
Revises: 2aaa7c358f98
Create Date: 2019-08-13 14:57:21.702574

"""

# revision identifiers, used by Alembic.
revision = '0379e7b740ec'
down_revision = '2aaa7c358f98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fechas', sa.Column('numero', sa.Integer(), nullable=True))
    op.drop_column('fechas', 'cantidad')
    op.add_column('partidos', sa.Column('pleno_personalizado', sa.Float(), nullable=True))
    op.add_column('partidos', sa.Column('punto_personalizado', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidos', 'punto_personalizado')
    op.drop_column('partidos', 'pleno_personalizado')
    op.add_column('fechas', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('fechas', 'numero')
    # ### end Alembic commands ###
