"""empty message

Revision ID: 687a20068d3a
Revises: 
Create Date: 2019-08-16 18:01:45.801133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687a20068d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('plenos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fechas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prode_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prode_id'], ['prodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_id', sa.Integer(), nullable=False),
    sa.Column('punto_personalizado', sa.Float(), nullable=True),
    sa.Column('pleno_personalizado', sa.Float(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('visitante', sa.String(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fecha_id'], ['fechas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronosticos')
    op.drop_table('partidos')
    op.drop_table('fechas')
    op.drop_table('prodes')
    op.drop_table('participantes')
    # ### end Alembic commands ###
