"""empty message

Revision ID: 8c26e52bcb49
Revises: None
Create Date: 2019-08-12 17:11:51.310197

"""

# revision identifiers, used by Alembic.
revision = '8c26e52bcb49'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('visitante', sa.String(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fecha_id'], ['Partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Fechas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prode_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prode_id'], ['prodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pronosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['Partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('plenos', sa.Integer(), nullable=True),
    sa.Column('prode_id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['prode_id'], ['prodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puntos')
    op.drop_table('Pronosticos')
    op.drop_table('Fechas')
    op.drop_table('prodes')
    op.drop_table('participantes')
    op.drop_table('Partidos')
    # ### end Alembic commands ###
