"""empty message

Revision ID: c37c5048133b
Revises: 687a20068d3a
Create Date: 2019-08-16 18:31:33.512250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37c5048133b'
down_revision = '687a20068d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participantes', sa.Column('prode_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'participantes', 'prodes', ['prode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participantes', type_='foreignkey')
    op.drop_column('participantes', 'prode_id')
    # ### end Alembic commands ###
