"""empty message

Revision ID: d24f3b3b22b5
Revises: fab7fba9fd92
Create Date: 2019-08-12 18:27:16.536045

"""

# revision identifiers, used by Alembic.
revision = 'd24f3b3b22b5'
down_revision = 'fab7fba9fd92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('partidos_fecha_id_fkey', 'partidos', type_='foreignkey')
    op.create_foreign_key(None, 'partidos', 'fechas', ['fecha_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidos', type_='foreignkey')
    op.create_foreign_key('partidos_fecha_id_fkey', 'partidos', 'partidos', ['fecha_id'], ['id'])
    # ### end Alembic commands ###
